// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2GlpVhwMHSlNOauGBLKonHRsq8gkth20',
    appId: '1:434745838925:web:04dad4b1f7029f5702fb04',
    messagingSenderId: '434745838925',
    projectId: 'todoapp-30f3e',
    authDomain: 'todoapp-30f3e.firebaseapp.com',
    storageBucket: 'todoapp-30f3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwrZ5kDcA5tv5VzSJrqwZsglgRihdGIOA',
    appId: '1:434745838925:android:69761a97db2b978702fb04',
    messagingSenderId: '434745838925',
    projectId: 'todoapp-30f3e',
    storageBucket: 'todoapp-30f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVauyNDCqIqD06-3W1oYuj9K0J7MsERRo',
    appId: '1:434745838925:ios:475ad6cd26fc1f6302fb04',
    messagingSenderId: '434745838925',
    projectId: 'todoapp-30f3e',
    storageBucket: 'todoapp-30f3e.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );
}
